version: '3'

services:
  app:
    container_name: meetup-app
    build:
      context: .
      dockerfile: Dockerfile.app.dev
    ports:
      - 8000:8000
  db:
    container_name: postgres-db
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/models/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
    ports:
      - 5433:5432
volumes:
  pgdata:
